In [5]:
import torch

x = torch.randn(32, 10) 
# print(x)      # batch of 32, 10 features each
# x = x.to("cuda")              # move to GPU
x = x.view(32, 2, 5) 
print(x)         # reshape
x = x.flatten(start_dim=1)    # back to [32, 10]
print(x)
print(x.shape)
print(x.dtype)
print(x.device)

tensor([[[ 1.2331e-01, -6.8587e-02,  1.1399e+00,  6.0420e-01, -2.6120e-02],
         [-2.2114e+00, -2.8717e-02, -1.0150e+00,  5.6643e-01, -6.3910e-01]],

        [[ 7.6841e-01,  5.6799e-01,  1.2992e+00, -1.0154e+00,  3.1767e-01],
         [-1.9699e-01, -3.9508e-01, -2.0768e-01, -1.0162e+00, -2.2745e-02]],

        [[-4.7748e-01,  6.4647e-01,  3.8823e-01,  1.2734e+00,  6.9422e-02],
         [-1.8012e-01,  4.8993e-01,  1.2910e+00, -8.5234e-01,  1.0567e+00]],

        [[ 1.8682e+00,  2.0163e+00,  6.9111e-01, -2.8717e-01, -1.5715e+00],
         [-3.1386e-01, -4.2124e-01, -8.2635e-02,  1.1599e+00, -9.4741e-01]],

        [[ 1.8240e-01,  1.5563e+00, -3.7845e-01, -4.3413e-01,  8.2786e-01],
         [-1.1649e+00, -7.4418e-01, -3.3889e-01, -1.9234e+00, -4.1254e-02]],

        [[ 1.1183e+00, -2.9093e-01, -6.5132e-01,  9.9820e-01,  1.0751e-01],
         [-4.0671e-01, -1.0817e+00,  3.3733e-01, -2.4937e-02,  1.8777e+00]],

        [[-1.4471e+00,  7.6655e-01,  1.0686e+00,  1.2041e+00, -4.6644e-01],


In [6]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(x)
print(x.shape)
print(x.dtype)
print(x.device)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
torch.int64
cpu


In [7]:
b = torch.tensor([1,2,3])
b+x

tensor([[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12]])

In [8]:
x = torch.rand(5)

In [9]:
x

tensor([0.2518, 0.2182, 0.8857, 0.2139, 0.1291])

In [11]:
x = torch.rand(5)
x

tensor([0.8290, 0.4953, 0.8209, 0.6308, 0.1672])

In [12]:
x = torch.arange(12).reshape(3, 4)
y = x.transpose(0, 1)

In [13]:
y

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [15]:
x = torch.arange(12).reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [16]:
x = torch.arange(12).reshape(3, 4)
y = x.transpose(0, 1)

print(y.shape)
# [4, 3]
print(id(x))
print(id(y))


torch.Size([4, 3])
126120791226976
126120790970496


In [17]:
predictions = torch.randn(1, 10)
predictions

tensor([[-1.8837,  1.2633, -0.5454, -0.4282,  1.1161,  0.6782,  0.3121, -1.3643,
         -1.1504, -0.4075]])

In [18]:
layer = torch.nn.Linear(10, 64)
x = torch.randn(32, 10)

output = layer(x)

In [19]:
print(output.shape)

torch.Size([32, 64])


In [20]:
print(output)







tensor([[-0.0638, -0.1086, -0.4584,  ...,  0.8525, -0.0089, -0.1484],
        [ 0.6126, -0.0559,  0.2837,  ...,  0.6463, -0.1893,  0.7874],
        [ 0.5782, -0.2483, -0.6228,  ..., -0.4902,  0.5808, -0.2127],
        ...,
        [ 0.4881, -0.3885, -0.4324,  ..., -0.3399,  1.2582,  0.2806],
        [ 0.3379,  0.5337, -0.4466,  ..., -0.6641,  0.4935, -0.5355],
        [ 0.1864,  0.2631, -0.1915,  ..., -0.7322,  0.9566, -0.3903]],
       grad_fn=<AddmmBackward0>)


In [21]:
manual_output = x @ layer.weight.T + layer.bias

In [22]:
manual_output

tensor([[-0.0638, -0.1086, -0.4584,  ...,  0.8525, -0.0089, -0.1484],
        [ 0.6126, -0.0559,  0.2837,  ...,  0.6463, -0.1893,  0.7874],
        [ 0.5782, -0.2483, -0.6228,  ..., -0.4902,  0.5808, -0.2127],
        ...,
        [ 0.4881, -0.3885, -0.4324,  ..., -0.3399,  1.2582,  0.2806],
        [ 0.3379,  0.5337, -0.4466,  ..., -0.6641,  0.4935, -0.5355],
        [ 0.1864,  0.2631, -0.1915,  ..., -0.7322,  0.9566, -0.3903]],
       grad_fn=<AddBackward0>)

In [28]:
weights = torch.randn(10,64)
bias = torch.randn(10)
x = torch.randn(32,64)

manual_output = x.matmul(weights.T) + bias
print(manual_output.shape)











torch.Size([32, 10])


In [34]:
x = torch.randn(8, 4,10, 3)
W = torch.randn(8, 4,3, 6)

output = torch.matmul(x, W)

In [35]:
output.shape

torch.Size([8, 4, 10, 6])

In [32]:
bb = x@W
bb.shape

torch.Size([8, 4, 6])

In [36]:
x = torch.randn(32, 4)
layer = torch.nn.Linear(
    in_features=4,
    out_features=10,
)

output = layer(x)

In [37]:
output.shape

torch.Size([32, 10])

In [38]:
logits = torch.randn(32, 5)

In [39]:
logits

tensor([[ 1.7656, -1.1263, -0.0339, -2.1643,  0.6939],
        [-0.4679, -0.0553, -1.4940, -0.7000, -2.8286],
        [-1.2184,  1.0757,  0.4458, -0.0285,  0.9181],
        [-0.7836,  0.4650, -1.3316,  0.5658, -0.5392],
        [ 1.0947,  0.4901,  0.2588,  0.3929, -0.3265],
        [-0.0345, -2.0793, -1.0887,  0.8173, -1.4498],
        [ 1.3556, -1.2710,  0.1523, -0.6997, -0.3281],
        [-0.2931, -0.8121,  1.4654,  1.5026, -0.3853],
        [-0.7480, -0.0340, -0.6376,  0.8962,  0.0812],
        [ 0.8862, -1.0867,  0.1249,  1.3680,  1.2423],
        [-0.5181, -0.0600,  1.7540,  0.7760,  0.1773],
        [-1.7357,  0.1839,  0.9863, -0.0256,  0.2355],
        [-0.3055,  0.0721,  0.1359,  0.4946, -0.3446],
        [ 0.2063,  2.3651, -0.0856, -1.7590, -0.6682],
        [ 0.0835,  1.3968,  0.0485,  1.9957, -0.5217],
        [ 0.6292,  0.4509,  0.2554,  2.0549, -0.1085],
        [-1.4016,  0.5277,  0.1598, -0.2364,  0.9859],
        [-1.9352,  1.2837,  1.3177, -1.4729, -0.9475],
        [-

In [40]:
predictions = logits.argmax(dim=1)

In [41]:
predictions

tensor([0, 1, 1, 3, 0, 3, 0, 3, 3, 3, 2, 2, 3, 1, 3, 3, 4, 2, 3, 0, 1, 0, 3, 1,
        4, 0, 2, 1, 4, 1, 3, 3])

In [42]:
layer = torch.nn.Linear(10, 5)

print(layer.weight.dtype)

torch.float32


In [43]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
])  # torch.int64

layer = torch.nn.Linear(3, 5)
output = layer(x)

RuntimeError: mat1 and mat2 must have the same dtype, but got Long and Float

In [58]:
logits = torch.randn(4, 3)
print(logits)
labels = torch.tensor([0, 2, 1, 0])
print(labels)

tensor([[-1.6748,  0.4626,  0.2169],
        [-0.2297, -0.8288,  1.1294],
        [ 0.1350, -0.4856, -0.2111],
        [-1.1786,  0.9721, -0.1882]])
tensor([0, 2, 1, 0])


In [59]:
labels

tensor([0, 2, 1, 0])

In [60]:
loss_fn = torch.nn.CrossEntropyLoss()
loss = loss_fn(logits, labels)

In [61]:
loss

tensor(1.7630)

In [62]:
token_ids = torch.tensor([
    [101, 2023, 2003, 102],
    [101, 1045, 2293, 102],
])
embedding = torch.nn.Embedding(
    num_embeddings=30000,
    embedding_dim=768,
)

vectors = embedding(token_ids)

In [65]:
vectors.shape

torch.Size([2, 4, 768])

In [66]:
vectors[0][0]

tensor([-5.4613e-01,  9.2141e-01, -2.5995e-01,  3.7873e-01,  2.3793e+00,
         2.7603e-02,  1.4768e+00, -8.9100e-01,  9.8429e-01, -1.2728e+00,
         1.9330e-01,  1.7056e-01,  1.2471e-01,  1.6252e+00, -1.4876e+00,
        -1.2035e+00,  8.8488e-01,  1.4807e+00,  2.6288e-01, -8.6639e-02,
        -8.4291e-01, -1.1042e+00,  1.4582e+00,  5.3469e-01,  3.2754e-01,
         9.5949e-01,  7.6179e-01, -3.7970e-02,  2.0200e+00, -7.4007e-01,
         9.3524e-01, -7.6217e-01, -1.0853e+00,  7.1244e-01,  3.2198e-01,
         7.3168e-01,  1.0916e+00, -4.1387e-02,  3.6905e-01,  9.0868e-01,
        -4.7718e-01, -9.9471e-02, -1.1710e+00, -9.0713e-01,  1.1515e+00,
         2.3348e+00,  1.6519e+00,  3.2505e-01, -1.1818e+00, -1.6418e+00,
        -7.7819e-01,  1.0426e+00, -8.6139e-01, -9.4427e-01, -3.3188e-01,
        -1.5894e+00,  6.8382e-01,  2.1173e+00,  5.9729e-01,  8.9708e-01,
         1.0005e+00,  2.4028e+00,  3.7009e-01,  8.8715e-02, -8.7753e-02,
         1.3044e+00, -1.0856e+00, -6.2506e-02, -2.0

In [67]:
x = torch.tensor(2.0, requires_grad=True)

y = x**2 + 3 * x
y.backward()

print(x.grad)  # dy/dx = 2x + 3 = 7

tensor(7.)


In [ ]:
x = torch.tensor(2.0, requires_grad=True)

y = x**2 + 3 * x
y.backward()

print(x.grad)  # dy/dx = 2x + 3 = 7

In [68]:
import torch

x = torch.tensor(2.0)
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)
y = torch.tensor(10.0)

z = w * x + b
loss = (z - y) ** 2

loss.backward()

print(w.grad)
print(b.grad)

tensor(-12.)
tensor(-6.)


In [71]:
print(w.grad)

tensor(-12.)


In [72]:
w = torch.tensor(0.5, requires_grad=True)
x= torch.tensor(1)
b= torch.tensor(0.5,requires_grad=True)
t= torch.tensor(1)


c = w*x
d = c+b
yhat= torch.sigmoid(d)
loss = (yhat-t)**2

loss.backward()

print(w.grad)
print(b.grad)




tensor(-0.1058)
tensor(-0.1058)


In [74]:
print(yhat.grad_fn)

In [ ]:
from 